version: '3'

services:
  ping-pong-bot:
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile-development
    env_file:
      - .env
    ports:
      - "80:3000"
      - "9229:9229"
    volumes:
      - ./server:/src/server
    privileged: true
